Readme update
BuildForSDGCohort2/Team-258-group-a-backend-php pull request #3
Opened 2020-09-11 13:22 UTC by sphezulu

i added intro, requirements, installation and a to do for the project. feedback welcome

2020-09-11 14:36 UTC, leanny01 commented on README.md
> +*	In the .env file fill in the - ![#f03c15](https://imgrp2.xiaolee.net/i/aHR0cHM6Ly9wbGFjZWhvbGQuaXQvMTUvZjAzYzE1LzAwMDAwMD90ZXh0PSs=.jpg) `DB_HOST `, ```javascript DB_PORT ```, ```javascript DB_DATA
I think a single quote will do the trick here.

2020-09-11 14:38 UTC, leanny01 commented on README.md
> +*   Clone the app on your computer using https://github.com/BuildForSDGCohort2/Team-258-group-a-backend-php)
I suggest we remove the link since we are on the same repo, I find it redundant that we have to share a  link that lead the same repo we are on.

2020-09-11 14:40 UTC, leanny01 requested changes
This is a good start, well done. There few details that need to be adjusted, please see my comments.

2020-09-11 15:12 UTC, sphezulu commented on README.md
> +*   Clone the app on your computer using https://github.com/BuildForSDGCohort2/Team-258-group-a-backend-php)
So this is just for the team?

2020-09-11 15:15 UTC, leanny01 commented on README.md
> +*   Clone the app on your computer using https://github.com/BuildForSDGCohort2/Team-258-group-a-backend-php)
I m referring to this line  -> `Clone the app on your computer using https://github.com/BuildForSDGCohort2/Team-258-group-a-backend-php)`

2020-09-11 16:38 UTC, Eunit99 approved these changes
Nice one @sphezulu.

2020-09-14 10:07 UTC, leanny01 approved these changes

2020-09-14 10:08 UTC, merged